import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

/*
   Practice String Calculator - Test Driven Development
 * This Java source file was generated by the Gradle 'init' task.
 */
public class StringCalculator {

    private final static String DELIMITER = "[,;\n]";

    public static void main(String[] args) {
        System.out.println("Hello String Calculator");
    }

    public int add(String input) {
        String[] inputTokens = input.split(DELIMITER);

        List<Integer> integers = Arrays
                                    .stream(inputTokens)
                                    .map(Integer::valueOf)
                                    .collect(Collectors.toList());

        return integers
                .stream()
                .mapToInt(i -> i)
                .sum();
    }
}