/*
   Practice String Calculator - Test Driven Development
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class StringCalculatorTest {

    @Test
    public void shouldReturnZeroForTheGivenInputZero() {
        int result = new StringCalculator().add("0");
        assertEquals(0, result);
    }

    @Test
    public void shouldReturnTheSameNumberForSingleInputValue() {
        int result = new StringCalculator().add("1234");
        assertEquals(1234, result);
    }

    @Test
    public void shouldReturnZeroForTheGivenInputZeroCommaZero() {
        int result = new StringCalculator().add("0,0");
        assertEquals(0, result);
    }

    @Test
    public void shouldReturnOneForTheGivenInputZeroCommaOne() {
        int result = new StringCalculator().add("0,1");
        assertEquals(1, result);
    }

    @Test
    public void shouldReturnSumOfTwoNumbersForTheGivenInputOneCommaTwo() {
        int result = new StringCalculator().add("1,2");
        assertEquals(3, result);
    }

    @Test
    public void shouldReturnTheSumeOfGivenNumbersForTheGivenNumbersWithMoreThanOneComma() {
        int result = new StringCalculator().add("1,2,3,4,5");
        assertEquals(15, result);
    }

    @Test
    public void shouldReturnZeroForTheGivenInputZeroNewLineZero() {
        int result = new StringCalculator().add("0\n0");
        assertEquals(0, result);
    }

    @Test
    public void shouldReturnOneForTheGivenInputZeroNewLineOne() {
        int result = new StringCalculator().add("0\n1");
        assertEquals(1, result);
    }

    @Test
    public void shouldReturnSumOfTwoNumbersForTheGivenInputOneNewLineTwo() {
        int result = new StringCalculator().add("1\n2");
        assertEquals(3, result);
    }

    @Test
    public void shouldReturnTheSumeOfGivenNumbersForTheGivenNumbersWithMoreThanOneNewLine() {
        int result = new StringCalculator().add("1\n2\n3\n4\n5");
        assertEquals(15, result);
    }

    @Test
    public void shouldReturnTheSumeOfGivenNumbersForTheGivenNumbersWithCommaAndNewLine() {
        int result = new StringCalculator().add("1,2\n3,4\n5");
        assertEquals(15, result);
    }

    @Test
    public void shouldReturnTheSumeOfGivenNumbersForTheGivenNumbersWithMoreThanOneSemiColon() {
        int result = new StringCalculator().add("1;2;3;4;5");
        assertEquals(15, result);
    }

    @Test
    public void shouldReturnTheSumeOfGivenNumbersForTheGivenNumbersWithNegative() {
        int result = new StringCalculator().add("-1;2;3;4;5");
        assertEquals(13, result);
    }
}
